-- Shared admin undo archive for deleted records
CREATE TABLE IF NOT EXISTS public.admin_deleted_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label TEXT NOT NULL,
  table_name TEXT NOT NULL,
  tab_key TEXT NOT NULL,
  payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  deleted_by TEXT,
  deleted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '30 days'),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_admin_deleted_records_deleted_at
  ON public.admin_deleted_records (deleted_at DESC);

CREATE INDEX IF NOT EXISTS idx_admin_deleted_records_expires_at
  ON public.admin_deleted_records (expires_at);

ALTER TABLE public.admin_deleted_records ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.is_admin_user()
RETURNS BOOLEAN
LANGUAGE sql
STABLE
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM auth.users
    WHERE auth.users.id = auth.uid()
      AND auth.users.raw_user_meta_data->>'role' = 'admin'
  )
  OR EXISTS (
    SELECT 1
    FROM public.user_profiles
    WHERE public.user_profiles.id = auth.uid()
      AND LOWER(COALESCE(public.user_profiles.role, '')) = 'admin'
  );
$$;

CREATE POLICY "Admins can read admin deleted records"
ON public.admin_deleted_records
FOR SELECT
USING (
  public.is_admin_user()
);

CREATE POLICY "Admins can insert admin deleted records"
ON public.admin_deleted_records
FOR INSERT
WITH CHECK (
  public.is_admin_user()
);

CREATE POLICY "Admins can update admin deleted records"
ON public.admin_deleted_records
FOR UPDATE
USING (
  public.is_admin_user()
)
WITH CHECK (
  public.is_admin_user()
);

CREATE POLICY "Admins can delete admin deleted records"
ON public.admin_deleted_records
FOR DELETE
USING (
  public.is_admin_user()
);

-- Optional utility for manual cleanup from SQL editor if needed
CREATE OR REPLACE FUNCTION public.cleanup_expired_admin_deleted_records()
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  removed_count INTEGER;
BEGIN
  DELETE FROM public.admin_deleted_records
  WHERE expires_at <= NOW();

  GET DIAGNOSTICS removed_count = ROW_COUNT;
  RETURN removed_count;
END;
$$;